#!/bin/sh

nohup java -jar /home/daq/src/cockpit/deploy/cockpit_linux64.jar -s localhost:30005 > /dev/null 2>&1 &
# java -jar /home/daq/src/cockpit/deploy/cockpit_linux64.jar -s localhost:30005

# -debug true
